### ISSUE TITLE
Error packaging

### ISSUE THREAD

**Issue by phyouthcenter1** [LengoLabs/qbot#124]
![image](https://user-images.githubusercontent.com/67077196/154378508-d91fe91d-11ce-438f-a3da-3996b5bf9d1c.png)

**Comment by phyouthcenter1** [comment]
![image](https://user-images.githubusercontent.com/67077196/154378598-71bc4ae3-b70e-42a8-9f7d-b7dfeebf237d.png)

**Comment by brandoge91** [comment]
in the shell, please run
```npm install --legacy-peer-deps```

**Comment by phyouthcenter1** [comment]
ok

**Comment by phyouthcenter1** [comment]
Nope. Didn't work.
![image](https://user-images.githubusercontent.com/67077196/154378750-7a5c1993-9e9b-449a-8620-cbf1f32d43f7.png)

**Comment by brandoge91** [comment]
you just hit the same button. please follow my instructions.

**Comment by phyouthcenter1** [comment]
i did run it

**Comment by phyouthcenter1** [comment]
i ran ur code, it finished, I pressed run and got that error

**Comment by brandoge91** [comment]
please send the output of you running it. the picutre you just sent above is the exact same command you ran earlier

**Comment by brandoge91** [comment]
ok

**Comment by phyouthcenter1** [comment]
![image](https://user-images.githubusercontent.com/67077196/154379003-a4d0b57e-bcdd-440f-84b2-a3e2e5a5f72d.png)

**Comment by brandoge91** [comment]
one minute, i am trying to reproduce your issue

**Comment by brandoge91** [comment]
i could not reproduce your issue. please try re-creating your repl and setting up again.

**Comment by phyouthcenter1** [comment]
can i fork it..?

**Comment by phyouthcenter1** [comment]
would the config cause this?

**Comment by phyouthcenter1** [comment]
i can send it

**Comment by brandoge91** [comment]
no. this is nothing to do with the config. please remake the repl using the setup guide and forking it will continue the issue

**Comment by phyouthcenter1** [comment]
ok.

**Comment by phyouthcenter1** [comment]
I am starting the new bot.

**Comment by phyouthcenter1** [comment]
It started! OMG THANK YOU SO MUCH!! :D

**Comment by phyouthcenter1** [comment]
[CLOSED]
