### ISSUE TITLE
Mongo Errors

### ISSUE THREAD

**Issue by phyouthcenter1** [LengoLabs/qbot#125]
https://user-images.githubusercontent.com/67077196/154398298-d2aa4cd9-d100-4799-a435-e677208587df.mp4

**Comment by phyouthcenter1** [comment]
The MongoNetworkTimeoutError occurs every time I run the bot.

**Comment by phyouthcenter1** [comment]
gp

**Comment by VIGHNESH-Y** [comment]
Use railway.

**Comment by phyouthcenter1** [comment]
k
