### ISSUE TITLE
Unable to rank

### ISSUE THREAD

**Issue by phyouthcenter1** [LengoLabs/qbot#126]
![image](https://user-images.githubusercontent.com/67077196/154409582-c4441fa0-dc21-4948-8e23-aba27dea7009.png)

**Comment by brandoge91** [comment]
is your database url correct? if you are using mongo atlas, please try railway

**Comment by phyouthcenter1** [comment]
Oh! Ok.

**Comment by phyouthcenter1** [comment]
fixed
