### ISSUE TITLE
The user doesn't exist in group

### ISSUE THREAD

**Issue by phyouthcenter1** [LengoLabs/qbot#127]
![image](https://user-images.githubusercontent.com/67077196/154515556-3f789d7f-faac-487a-8c26-84f153acb370.png)
![image](https://user-images.githubusercontent.com/67077196/154515608-52c83214-deb2-432b-9d41-fd451a7b9d7d.png)

**Comment by phyouthcenter1** [comment]
Sus

**Comment by phyouthcenter1** [comment]
p

**Comment by VIGHNESH-Y** [comment]
Try using Slash Commands

**Comment by Alfred-207** [comment]
This issue is because you have a space in between your double dashes and reason. Try >promote PjSocoolhaa --Testing

**Comment by wilyt1** [comment]
The syntax for the promote command is `>promote <roblox-user> --reason=<reason>`.

**Comment by phyouthcenter1** [comment]
ok
